### ISSUE TITLE
Getting Traceback Error: 'ModuleNotFoundError: No module named 'triton.language' (On Wondows) All requirements correctly Installed

### ISSUE THREAD

**Issue by jjaitley** [PromtEngineer/localGPT-Vision#27]
```
(vision-rag) C:\Users\jatin\AI_projects\localGPT-Vision>python app.py
WARNING 12-08 23:55:52 _custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Traceback (most recent call last):
  File "C:\Users\jatin\AI_projects\localGPT-Vision\app.py", line 9, in <module>
    from models.responder import generate_response
  File "C:\Users\jatin\AI_projects\localGPT-Vision\models\responder.py", line 3, in <module>
    from models.model_loader import load_model, is_single_image_model
  File "C:\Users\jatin\AI_projects\localGPT-Vision\models\model_loader.py", line 7, in <module>
    from vllm.sampling_params import SamplingParams
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\engine\arg_utils.py", line 11, in <module>
    from vllm.config import (CacheConfig, ConfigFormat, DecodingConfig,
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\config.py", line 14, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\model_executor\layers\quantization\__init__.py", line 5, in <module>
    from vllm.model_executor.layers.quantization.awq_marlin import AWQMarlinConfig
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\model_executor\layers\quantization\awq_marlin.py", line 6, in <module>
    import vllm.model_executor.layers.fused_moe  # noqa
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\model_executor\layers\fused_moe\__init__.py", line 4, in <module>
    from vllm.model_executor.layers.fused_moe.layer import (
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\model_executor\layers\fused_moe\layer.py", line 18, in <module>
    from .fused_moe import fused_experts
  File "C:\Users\jatin\anaconda3\envs\vision-rag\lib\site-packages\vllm\model_executor\layers\fused_moe\fused_moe.py", line 9, in <module>
    import triton.language as tl
ModuleNotFoundError: No module named 'triton.language'
```

**Comment by jjaitley** [comment]
tried twice here is the error I am getting. FYI: No errors while running the requirements.txt file.

`(vrag) C:\Users\jatin\AI_projects\VRAG>python app.py
WARNING 12-09 01:52:05 _custom_ops.py:20] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Traceback (most recent call last):
  File "C:\Users\jatin\AI_projects\VRAG\app.py", line 9, in <module>
    from models.responder import generate_response
  File "C:\Users\jatin\AI_projects\VRAG\models\responder.py", line 3, in <module>
    from models.model_loader import load_model, is_single_image_model
  File "C:\Users\jatin\AI_projects\VRAG\models\model_loader.py", line 7, in <module>
    from vllm.sampling_params import SamplingParams
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\__init__.py", line 3, in <module>
    from vllm.engine.arg_utils import AsyncEngineArgs, EngineArgs
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\engine\arg_utils.py", line 11, in <module>
    from vllm.config import (CacheConfig, ConfigFormat, DecodingConfig,
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\config.py", line 14, in <module>
    from vllm.model_executor.layers.quantization import QUANTIZATION_METHODS
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\model_executor\layers\quantization\__init__.py", line 5, in <module>
    from vllm.model_executor.layers.quantization.awq_marlin import AWQMarlinConfig
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\model_executor\layers\quantization\awq_marlin.py", line 6, in <module>
    import vllm.model_executor.layers.fused_moe  # noqa
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\model_executor\layers\fused_moe\__init__.py", line 4, in <module>
    from vllm.model_executor.layers.fused_moe.layer import (
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\model_executor\layers\fused_moe\layer.py", line 18, in <module>
    from .fused_moe import fused_experts
  File "C:\Users\jatin\anaconda3\envs\vrag\lib\site-packages\vllm\model_executor\layers\fused_moe\fused_moe.py", line 8, in <module>
    import triton
ModuleNotFoundError: No module named 'triton'

(vrag) C:\Users\jatin\AI_projects\VRAG>pip show vllm
Name: vllm
Version: 0.6.4.post1
Summary: A high-throughput and memory-efficient inference and serving engine for LLMs
Home-page: https://github.com/vllm-project/vllm
Author: vLLM Team
Author-email:
License: Apache 2.0
Location: c:\users\jatin\anaconda3\envs\vrag\lib\site-packages
Requires: aiohttp, compressed-tensors, einops, fastapi, filelock, gguf, importlib_metadata, lm-format-enforcer, mistral_common, msgspec, numpy, nvidia-ml-py, openai, outlines, partial-json-parser, pillow, prometheus-fastapi-instrumentator, prometheus_client, protobuf, psutil, py-cpuinfo, pydantic, pyyaml, pyzmq, ray, requests, sentencepiece, tiktoken, tokenizers, torch, torchvision, tqdm, transformers, typing_extensions, uvicorn
Required-by:
`
